M48
; DRILL file {KiCad 9.0.1} date 2025-08-26T09:45:28+0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-08-26T09:45:28+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X6.776Y-2.8
T2
X6.0Y-2.324
X6.136Y-9.536
X9.34Y-2.324
X9.35Y-9.536
M30
